### PR TITLE
chore: upgrade pkg-dir

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by benmccann** [comment]
@bluelovers any chance you might be able to take a look at this?

**Comment by bluelovers** [comment]
> @bluelovers any chance you might be able to take a look at this?

any issues u need this update？

**Comment by benmccann** [comment]
It allows dependencies to be deduped. My other dependencies are on the latest version. This one is restricted to an old version, which causes multiple versions to be in my dependency tree

**Comment by bluelovers** [comment]
new version only has esm, that will make some old can't work

**Comment by benmccann** [comment]
Ah, I see. I will close this for now then. Thank you for taking a look

**Pull request closed without merging**
